-- Historical prototype schema only.
--
-- The current storefront uses the shared Smokehouse operational schema from
-- the admin repo (`thesmokehouse-admin/db`). Do not apply this file to a
-- current Smokehouse Supabase project.
--
-- Required shared-schema phases for storefront checkout include:
-- - phase-10-storefront-shared-order-support.sql
-- - phase-19-order-lifecycle-simplification.sql
-- - phase-21-pesapal-paid-reservations.sql
-- - phase-22-admin-rls-lockdown.sql
-- - phase-23-orders-realtime-publication.sql
